[[redirects]]
  from = "/"
  to = "https://thepage-gfork.zh-hk.eu.org/404"
  status = 200
  force = true

[[redirects]]
  from = "/ads.txt"
  to = "https://thepage-gfork.zh-hk.eu.org/ads.txt"
  status = 200
  force = true

[[redirects]]
  from = "/404"
  to = "https://thepage-gfork.zh-hk.eu.org/404"
  status = 200
  force = true

[[redirects]]
  from = "/favicon.ico"
  to = "https://thepage-gfork.zh-hk.eu.org/favicon.ico"
  status = 308
  force = true
  
[[redirects]]
  from = "/s"
  to = "https://thepage-gfork.zh-hk.eu.org/searchw"
  status = 200
  force = true

[[redirects]]
  from = "/p/1E3F8A9F-DDC6-4D76-B101-5683AA13E349"
  to = "https://dgkkhxhkj.dahi.edu.eu.org/zh-CN/scripts.json"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "https://greasyfork.org.cn/:splat"
  status = 308
